### ISSUE TITLE
ISA Ontology Annotations

### ISSUE THREAD

**Issue by ptth222** [MoseleyBioinformaticsLab/MESSES#25]
We had previously discussed this and you came up with a format like "source:accession:value:comment". For example, OBI:0500020:time series design:comment. We had talked about being able to take something as simple as OBI:0500020:: or OBI::time series design: and fill in the rest by going to the web. I guess what I want to know is how much effort and priority to put into this.

The easiest thing that solves the problem for now is to simply take whatever the user provides in those positions and translate it straight into the dictionary form that ISA wants. To try and create appropriate URLs and fill in other values though is a significant amount more work. We could start with the simple way first and add the extra stuff later, but this would not be backwards compatible. I think we would need something like dumb_parse_ontolgy_annotation() and smart_parse_ontology_annotation().

What do you think?

**Comment by hunter-moseley** [comment]
I agree.  
Divide and conquer.  Do the dumb parsing that requires complete information and then later add smart parsing that attempts to validate and fill in missing information.

**Comment by ptth222** [comment]
dumb_parse is created and I added a todo to create a smart_parse in the documentation.
